### ISSUE TITLE
License Project

### ISSUE THREAD

**Issue by williamfligor** [gsmecher/pyxsi#1]
Would you consider licensing this source code under MIT, BSD, etc? Currently there is no OSS license specified that I could fine.

**Comment by gsmecher** [comment]
Hi William,

I've added a BSD 3-clause license for the portions I control. I didn't do this originally because the XSI library wrapper code comes unlicensed from Xilinx -- please take a look at how I've threaded the needle and comment if you like.

cheers,
Graeme

**Comment by williamfligor** [comment]
This is great! Thank you!
