### ISSUE TITLE
Xilinx IP support?

### ISSUE THREAD

**Issue by FiberQP** [gsmecher/pyxsi#4]
Hi there!

This project is pretty great!
Have played around with the example a bit.

I was wondering if it's possible to support code with Xilinx IP cores? I should, right?
In that case, do you have any example?

Cheers, William

**Comment by FiberQP** [comment]
@gsmecher 
Any input on this?

**Comment by gsmecher** [comment]
Hi William,

You can absolutely use xilinx IP (FFT, FIR, etc) - it should be no
different than any other RTL code.

I don't have specific examples, but if you get stuck somewhere, please post
what you're trying and I'll take a look.

Best,
Graeme
